# Generated by Django 5.0.6 on 2024-10-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_attendance_session_alter_attendance_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='students',
            field=models.ManyToManyField(blank=True, to='home.studentprofile'),
        ),
    ]
